language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"

matrix:
  exclude:

sudo: false

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
