dist: xenial

addons:
  apt:
    packages:
      - ant-optional

language: php

php:
  - "7.3"
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

matrix:
  exclude:

sudo: false

install:
  - echo "memory_limit = -1" > travis.php.ini && phpenv config-add travis.php.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --prefer-dist --no-interaction

script: ant -keep-going

git:
  depth: 2147483647

cache:
  directories:
    - vendor
